// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiVtXhHM_tUbNrIn9KjRVq7K9uSBpj1pU',
    appId: '1:311379764419:web:ca7d55c84e10737c906e76',
    messagingSenderId: '311379764419',
    projectId: 'mintycard-97j73q',
    authDomain: 'mintycard-97j73q.firebaseapp.com',
    storageBucket: 'mintycard-97j73q.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE-RdwiShUvaFwufve684-0ET_QBbWzqk',
    appId: '1:311379764419:android:ca52fb3ec682dfda906e76',
    messagingSenderId: '311379764419',
    projectId: 'mintycard-97j73q',
    storageBucket: 'mintycard-97j73q.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQYxON_HLXr-vercJR_tBpWSW9GlEPrOQ',
    appId: '1:311379764419:ios:9159e00afd81cf46906e76',
    messagingSenderId: '311379764419',
    projectId: 'mintycard-97j73q',
    storageBucket: 'mintycard-97j73q.firebasestorage.app',
    iosBundleId: 'com.example.marketplacePokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQYxON_HLXr-vercJR_tBpWSW9GlEPrOQ',
    appId: '1:311379764419:ios:9159e00afd81cf46906e76',
    messagingSenderId: '311379764419',
    projectId: 'mintycard-97j73q',
    storageBucket: 'mintycard-97j73q.firebasestorage.app',
    iosBundleId: 'com.example.marketplacePokemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiVtXhHM_tUbNrIn9KjRVq7K9uSBpj1pU',
    appId: '1:311379764419:web:6b0f36b794306f90906e76',
    messagingSenderId: '311379764419',
    projectId: 'mintycard-97j73q',
    authDomain: 'mintycard-97j73q.firebaseapp.com',
    storageBucket: 'mintycard-97j73q.firebasestorage.app',
  );
}
